services: mongodb

notifications:
  email: false

language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  
gemfile:
  - Gemfile
  - gemfiles/mongoid-3.0.gemfile
  - gemfiles/mongoid-3.1.gemfile
  - gemfiles/mongoid-4.0.gemfile
